/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ComeFunzionaRouteImport } from './routes/come-funziona'
import { Route as CentriEstiviRouteImport } from './routes/centri-estivi'
import { Route as AreaStaffRouteImport } from './routes/area-staff'
import { Route as AreaGenitoriRouteImport } from './routes/area-genitori'
import { Route as AreaAdminRouteImport } from './routes/area-admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CentriEstiviSlugRouteImport } from './routes/centri-estivi.$slug'

const ComeFunzionaRoute = ComeFunzionaRouteImport.update({
  id: '/come-funziona',
  path: '/come-funziona',
  getParentRoute: () => rootRouteImport,
} as any)
const CentriEstiviRoute = CentriEstiviRouteImport.update({
  id: '/centri-estivi',
  path: '/centri-estivi',
  getParentRoute: () => rootRouteImport,
} as any)
const AreaStaffRoute = AreaStaffRouteImport.update({
  id: '/area-staff',
  path: '/area-staff',
  getParentRoute: () => rootRouteImport,
} as any)
const AreaGenitoriRoute = AreaGenitoriRouteImport.update({
  id: '/area-genitori',
  path: '/area-genitori',
  getParentRoute: () => rootRouteImport,
} as any)
const AreaAdminRoute = AreaAdminRouteImport.update({
  id: '/area-admin',
  path: '/area-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CentriEstiviSlugRoute = CentriEstiviSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CentriEstiviRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/area-admin': typeof AreaAdminRoute
  '/area-genitori': typeof AreaGenitoriRoute
  '/area-staff': typeof AreaStaffRoute
  '/centri-estivi': typeof CentriEstiviRouteWithChildren
  '/come-funziona': typeof ComeFunzionaRoute
  '/centri-estivi/$slug': typeof CentriEstiviSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/area-admin': typeof AreaAdminRoute
  '/area-genitori': typeof AreaGenitoriRoute
  '/area-staff': typeof AreaStaffRoute
  '/centri-estivi': typeof CentriEstiviRouteWithChildren
  '/come-funziona': typeof ComeFunzionaRoute
  '/centri-estivi/$slug': typeof CentriEstiviSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/area-admin': typeof AreaAdminRoute
  '/area-genitori': typeof AreaGenitoriRoute
  '/area-staff': typeof AreaStaffRoute
  '/centri-estivi': typeof CentriEstiviRouteWithChildren
  '/come-funziona': typeof ComeFunzionaRoute
  '/centri-estivi/$slug': typeof CentriEstiviSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/area-admin'
    | '/area-genitori'
    | '/area-staff'
    | '/centri-estivi'
    | '/come-funziona'
    | '/centri-estivi/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/area-admin'
    | '/area-genitori'
    | '/area-staff'
    | '/centri-estivi'
    | '/come-funziona'
    | '/centri-estivi/$slug'
  id:
    | '__root__'
    | '/'
    | '/area-admin'
    | '/area-genitori'
    | '/area-staff'
    | '/centri-estivi'
    | '/come-funziona'
    | '/centri-estivi/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AreaAdminRoute: typeof AreaAdminRoute
  AreaGenitoriRoute: typeof AreaGenitoriRoute
  AreaStaffRoute: typeof AreaStaffRoute
  CentriEstiviRoute: typeof CentriEstiviRouteWithChildren
  ComeFunzionaRoute: typeof ComeFunzionaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/come-funziona': {
      id: '/come-funziona'
      path: '/come-funziona'
      fullPath: '/come-funziona'
      preLoaderRoute: typeof ComeFunzionaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/centri-estivi': {
      id: '/centri-estivi'
      path: '/centri-estivi'
      fullPath: '/centri-estivi'
      preLoaderRoute: typeof CentriEstiviRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/area-staff': {
      id: '/area-staff'
      path: '/area-staff'
      fullPath: '/area-staff'
      preLoaderRoute: typeof AreaStaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/area-genitori': {
      id: '/area-genitori'
      path: '/area-genitori'
      fullPath: '/area-genitori'
      preLoaderRoute: typeof AreaGenitoriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/area-admin': {
      id: '/area-admin'
      path: '/area-admin'
      fullPath: '/area-admin'
      preLoaderRoute: typeof AreaAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/centri-estivi/$slug': {
      id: '/centri-estivi/$slug'
      path: '/$slug'
      fullPath: '/centri-estivi/$slug'
      preLoaderRoute: typeof CentriEstiviSlugRouteImport
      parentRoute: typeof CentriEstiviRoute
    }
  }
}

interface CentriEstiviRouteChildren {
  CentriEstiviSlugRoute: typeof CentriEstiviSlugRoute
}

const CentriEstiviRouteChildren: CentriEstiviRouteChildren = {
  CentriEstiviSlugRoute: CentriEstiviSlugRoute,
}

const CentriEstiviRouteWithChildren = CentriEstiviRoute._addFileChildren(
  CentriEstiviRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AreaAdminRoute: AreaAdminRoute,
  AreaGenitoriRoute: AreaGenitoriRoute,
  AreaStaffRoute: AreaStaffRoute,
  CentriEstiviRoute: CentriEstiviRouteWithChildren,
  ComeFunzionaRoute: ComeFunzionaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
