/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PasswordDimenticataRouteImport } from './routes/password-dimenticata'
import { Route as NonAutorizzatoRouteImport } from './routes/non-autorizzato'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ComeFunzionaRouteImport } from './routes/come-funziona'
import { Route as CentriEstiviRouteImport } from './routes/centri-estivi'
import { Route as AreaStaffRouteImport } from './routes/area-staff'
import { Route as AreaGenitoriRouteImport } from './routes/area-genitori'
import { Route as AreaAdminRouteImport } from './routes/area-admin'
import { Route as AggiornaPasswordRouteImport } from './routes/aggiorna-password'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CentriEstiviSlugRouteImport } from './routes/centri-estivi_.$slug'
import { Route as CentriEstiviSlugIscrizioneRouteImport } from './routes/centri-estivi_.$slug_.iscrizione'

const PasswordDimenticataRoute = PasswordDimenticataRouteImport.update({
  id: '/password-dimenticata',
  path: '/password-dimenticata',
  getParentRoute: () => rootRouteImport,
} as any)
const NonAutorizzatoRoute = NonAutorizzatoRouteImport.update({
  id: '/non-autorizzato',
  path: '/non-autorizzato',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ComeFunzionaRoute = ComeFunzionaRouteImport.update({
  id: '/come-funziona',
  path: '/come-funziona',
  getParentRoute: () => rootRouteImport,
} as any)
const CentriEstiviRoute = CentriEstiviRouteImport.update({
  id: '/centri-estivi',
  path: '/centri-estivi',
  getParentRoute: () => rootRouteImport,
} as any)
const AreaStaffRoute = AreaStaffRouteImport.update({
  id: '/area-staff',
  path: '/area-staff',
  getParentRoute: () => rootRouteImport,
} as any)
const AreaGenitoriRoute = AreaGenitoriRouteImport.update({
  id: '/area-genitori',
  path: '/area-genitori',
  getParentRoute: () => rootRouteImport,
} as any)
const AreaAdminRoute = AreaAdminRouteImport.update({
  id: '/area-admin',
  path: '/area-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AggiornaPasswordRoute = AggiornaPasswordRouteImport.update({
  id: '/aggiorna-password',
  path: '/aggiorna-password',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CentriEstiviSlugRoute = CentriEstiviSlugRouteImport.update({
  id: '/centri-estivi_/$slug',
  path: '/centri-estivi/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CentriEstiviSlugIscrizioneRoute =
  CentriEstiviSlugIscrizioneRouteImport.update({
    id: '/centri-estivi_/$slug_/iscrizione',
    path: '/centri-estivi/$slug/iscrizione',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aggiorna-password': typeof AggiornaPasswordRoute
  '/area-admin': typeof AreaAdminRoute
  '/area-genitori': typeof AreaGenitoriRoute
  '/area-staff': typeof AreaStaffRoute
  '/centri-estivi': typeof CentriEstiviRoute
  '/come-funziona': typeof ComeFunzionaRoute
  '/login': typeof LoginRoute
  '/non-autorizzato': typeof NonAutorizzatoRoute
  '/password-dimenticata': typeof PasswordDimenticataRoute
  '/centri-estivi/$slug': typeof CentriEstiviSlugRoute
  '/centri-estivi/$slug/iscrizione': typeof CentriEstiviSlugIscrizioneRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aggiorna-password': typeof AggiornaPasswordRoute
  '/area-admin': typeof AreaAdminRoute
  '/area-genitori': typeof AreaGenitoriRoute
  '/area-staff': typeof AreaStaffRoute
  '/centri-estivi': typeof CentriEstiviRoute
  '/come-funziona': typeof ComeFunzionaRoute
  '/login': typeof LoginRoute
  '/non-autorizzato': typeof NonAutorizzatoRoute
  '/password-dimenticata': typeof PasswordDimenticataRoute
  '/centri-estivi/$slug': typeof CentriEstiviSlugRoute
  '/centri-estivi/$slug/iscrizione': typeof CentriEstiviSlugIscrizioneRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aggiorna-password': typeof AggiornaPasswordRoute
  '/area-admin': typeof AreaAdminRoute
  '/area-genitori': typeof AreaGenitoriRoute
  '/area-staff': typeof AreaStaffRoute
  '/centri-estivi': typeof CentriEstiviRoute
  '/come-funziona': typeof ComeFunzionaRoute
  '/login': typeof LoginRoute
  '/non-autorizzato': typeof NonAutorizzatoRoute
  '/password-dimenticata': typeof PasswordDimenticataRoute
  '/centri-estivi_/$slug': typeof CentriEstiviSlugRoute
  '/centri-estivi_/$slug_/iscrizione': typeof CentriEstiviSlugIscrizioneRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aggiorna-password'
    | '/area-admin'
    | '/area-genitori'
    | '/area-staff'
    | '/centri-estivi'
    | '/come-funziona'
    | '/login'
    | '/non-autorizzato'
    | '/password-dimenticata'
    | '/centri-estivi/$slug'
    | '/centri-estivi/$slug/iscrizione'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aggiorna-password'
    | '/area-admin'
    | '/area-genitori'
    | '/area-staff'
    | '/centri-estivi'
    | '/come-funziona'
    | '/login'
    | '/non-autorizzato'
    | '/password-dimenticata'
    | '/centri-estivi/$slug'
    | '/centri-estivi/$slug/iscrizione'
  id:
    | '__root__'
    | '/'
    | '/aggiorna-password'
    | '/area-admin'
    | '/area-genitori'
    | '/area-staff'
    | '/centri-estivi'
    | '/come-funziona'
    | '/login'
    | '/non-autorizzato'
    | '/password-dimenticata'
    | '/centri-estivi_/$slug'
    | '/centri-estivi_/$slug_/iscrizione'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AggiornaPasswordRoute: typeof AggiornaPasswordRoute
  AreaAdminRoute: typeof AreaAdminRoute
  AreaGenitoriRoute: typeof AreaGenitoriRoute
  AreaStaffRoute: typeof AreaStaffRoute
  CentriEstiviRoute: typeof CentriEstiviRoute
  ComeFunzionaRoute: typeof ComeFunzionaRoute
  LoginRoute: typeof LoginRoute
  NonAutorizzatoRoute: typeof NonAutorizzatoRoute
  PasswordDimenticataRoute: typeof PasswordDimenticataRoute
  CentriEstiviSlugRoute: typeof CentriEstiviSlugRoute
  CentriEstiviSlugIscrizioneRoute: typeof CentriEstiviSlugIscrizioneRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/password-dimenticata': {
      id: '/password-dimenticata'
      path: '/password-dimenticata'
      fullPath: '/password-dimenticata'
      preLoaderRoute: typeof PasswordDimenticataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/non-autorizzato': {
      id: '/non-autorizzato'
      path: '/non-autorizzato'
      fullPath: '/non-autorizzato'
      preLoaderRoute: typeof NonAutorizzatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/come-funziona': {
      id: '/come-funziona'
      path: '/come-funziona'
      fullPath: '/come-funziona'
      preLoaderRoute: typeof ComeFunzionaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/centri-estivi': {
      id: '/centri-estivi'
      path: '/centri-estivi'
      fullPath: '/centri-estivi'
      preLoaderRoute: typeof CentriEstiviRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/area-staff': {
      id: '/area-staff'
      path: '/area-staff'
      fullPath: '/area-staff'
      preLoaderRoute: typeof AreaStaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/area-genitori': {
      id: '/area-genitori'
      path: '/area-genitori'
      fullPath: '/area-genitori'
      preLoaderRoute: typeof AreaGenitoriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/area-admin': {
      id: '/area-admin'
      path: '/area-admin'
      fullPath: '/area-admin'
      preLoaderRoute: typeof AreaAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aggiorna-password': {
      id: '/aggiorna-password'
      path: '/aggiorna-password'
      fullPath: '/aggiorna-password'
      preLoaderRoute: typeof AggiornaPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/centri-estivi_/$slug': {
      id: '/centri-estivi_/$slug'
      path: '/centri-estivi/$slug'
      fullPath: '/centri-estivi/$slug'
      preLoaderRoute: typeof CentriEstiviSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/centri-estivi_/$slug_/iscrizione': {
      id: '/centri-estivi_/$slug_/iscrizione'
      path: '/centri-estivi/$slug/iscrizione'
      fullPath: '/centri-estivi/$slug/iscrizione'
      preLoaderRoute: typeof CentriEstiviSlugIscrizioneRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AggiornaPasswordRoute: AggiornaPasswordRoute,
  AreaAdminRoute: AreaAdminRoute,
  AreaGenitoriRoute: AreaGenitoriRoute,
  AreaStaffRoute: AreaStaffRoute,
  CentriEstiviRoute: CentriEstiviRoute,
  ComeFunzionaRoute: ComeFunzionaRoute,
  LoginRoute: LoginRoute,
  NonAutorizzatoRoute: NonAutorizzatoRoute,
  PasswordDimenticataRoute: PasswordDimenticataRoute,
  CentriEstiviSlugRoute: CentriEstiviSlugRoute,
  CentriEstiviSlugIscrizioneRoute: CentriEstiviSlugIscrizioneRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
