/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ComeFunzionaRouteImport } from './routes/come-funziona'
import { Route as CentriEstiviRouteImport } from './routes/centri-estivi'
import { Route as IndexRouteImport } from './routes/index'

const ComeFunzionaRoute = ComeFunzionaRouteImport.update({
  id: '/come-funziona',
  path: '/come-funziona',
  getParentRoute: () => rootRouteImport,
} as any)
const CentriEstiviRoute = CentriEstiviRouteImport.update({
  id: '/centri-estivi',
  path: '/centri-estivi',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/centri-estivi': typeof CentriEstiviRoute
  '/come-funziona': typeof ComeFunzionaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/centri-estivi': typeof CentriEstiviRoute
  '/come-funziona': typeof ComeFunzionaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/centri-estivi': typeof CentriEstiviRoute
  '/come-funziona': typeof ComeFunzionaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/centri-estivi' | '/come-funziona'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/centri-estivi' | '/come-funziona'
  id: '__root__' | '/' | '/centri-estivi' | '/come-funziona'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CentriEstiviRoute: typeof CentriEstiviRoute
  ComeFunzionaRoute: typeof ComeFunzionaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/come-funziona': {
      id: '/come-funziona'
      path: '/come-funziona'
      fullPath: '/come-funziona'
      preLoaderRoute: typeof ComeFunzionaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/centri-estivi': {
      id: '/centri-estivi'
      path: '/centri-estivi'
      fullPath: '/centri-estivi'
      preLoaderRoute: typeof CentriEstiviRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CentriEstiviRoute: CentriEstiviRoute,
  ComeFunzionaRoute: ComeFunzionaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
