// This file is automatically generated. Do not edit it directly.
// Uso il singleton browser client dell'app per evitare più istanze di
// GoTrueClient nello stesso contesto browser.
import { createMiddleware } from '@tanstack/react-start'
import { getSupabaseBrowserClient } from '@/lib/supabase/client'

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
    const { data } = await getSupabaseBrowserClient().auth.getSession()
    const token = data.session?.access_token
    return next({
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    })
  },
)
